<?php
    $this->headTitle($this->translate('Text only'));
    $this->placeholder('headerContent')->set('Edit text only content');
    $this->placeholder('containerId')->set('webbuilder-text-only');
?>
<form id="text-only" action="<?php echo $this->websiteUrl;?>api/webbuilder/to/" method="post" class="_fajax _reload">
    <textarea id="text-only-content" name="content" class="tinymce"><?php echo $this->content; ?></textarea>
    <input id="submit" name="submit" type="submit" value="<?php echo $this->translate('Save content'); ?>" />
    <input type="hidden" id="containerName" name="containerName" value="<?php echo $this->containerName; ?>"/>
    <input type="hidden" id="pageId" name="pageId" value="<?php echo $this->pageId;?>"/>
</form>
<style type="text/css">
    textarea#text-only-content {width: 613px;height: 410px;}
    #text-only #submit {margin: 2px 0;}
</style>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/tinymce/jquery.tinymce.js'); ?>
<script type="text/javascript">
    $('textarea.tinymce').tinymce({
        script_url                      : '<?php echo $this->websiteUrl; ?>system/js/external/tinymce/tiny_mce_gzip.php',
        plugins                         : 'style,paste,example',
        theme                           : 'advanced',
        elements                        : 'nourlconvert',
        theme_advanced_buttons1         : 'bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect, formatselect,|,pastetext,bullist,numlist,|,link,unlink,anchor,code,forecolor,backcolor,',
        theme_advanced_buttons2         : '',
        theme_advanced_buttons3         : '',
        theme_advanced_toolbar_location : 'top',
        theme_advanced_toolbar_align    : 'left',
        theme_advanced_resizing         : false,
        convert_urls                    : 0,
        entity_encoding                 : 'raw',
        paste_auto_cleanup_on_paste     : true,
        paste_remove_styles             : true,
        content_css                     : '<?php echo $this->websiteUrl; ?>themes/<?php echo $this->currentTheme; ?>/content.css',
        disk_cache                      : false,
        debug                           : false,
        force_br_newlines               : false,
        force_p_newlines                : true,
        forced_root_block               : '',
        valid_elements                  : '*[*]'
    });
</script>

 