<?php if(isset($this->totalQuotes)):?>
    <div class="totalQuotes"><?php echo $this->totalQuotes;?></div>
<?php endif; ?>
<?php if(isset($this->quotesFromPeriod)):?>
    <div class="quotesFromPeriod"><?php echo $this->quotesFromPeriod;?></div>
<?php endif; ?>
<?php if(isset($this->quotesToday)):?>
    <div class="quotesToday fs64 green"><?php echo $this->quotesToday;?></div>
<?php endif; ?>