<?php echo $this->doctype();?>
<html>
    <head>
	    <?php
		    $this->headMeta()->setCharset('UTF-8');
	        $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
                 ->appendHttpEquiv('Content-Language', $this->translate()->getLocale());

	        echo $this->headMeta();

            echo $this->headTitle();

	        $this->headLink()->appendStylesheet($this->websiteUrl . 'system/uithemes/seotoasterui/seotoasterui.css')
		        ->appendStylesheet($this->websiteUrl . 'system/css/reset.css')
		        ->appendStylesheet($this->websiteUrl . 'system/css/grid.css')
                ->appendStylesheet($this->websiteUrl . 'system/css/seotoaster.css')
                ->appendStylesheet($this->websiteUrl . 'system/js/external/smoke/smoke.css')
				->appendStylesheet($this->websiteUrl . 'plugins/widcard/system/css/widcard.css');

            echo $this->headLink();

	        echo $this->headStyle();

	        $this->jQuery()->enable();
            $this->jQuery()->uiEnable();

	        $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js')
			    ->addJavascriptFile($this->websiteUrl . 'system/js/external/smoke/smoke.min.js')
	            ->addJavascriptFile($this->websiteUrl . 'system/js/external/jquery/plugins/cookie/jquery.cookie.js')
			    ->addJavascriptFile($this->websiteUrl . 'system/js/internal/system.js')
				->addJavascriptFile($this->websiteUrl."system/js/external/plupload/plupload.js")
				->addJavascriptFile($this->websiteUrl."system/js/external/plupload/plupload.html5.js")
				->addJavascriptFile($this->websiteUrl."system/js/external/plupload/plupload.html4.js")
				->addJavascriptFile($this->websiteUrl."system/js/external/plupload/plupload.flash.js")
				->addJavascriptFile($this->websiteUrl . 'plugins/widcard/system/js/widcard.js');

	        echo $this->jQuery();

            $this->headScript()->setAllowArbitraryAttributes(true);
	        echo $this->headScript();
        ?>
	</head>
    <body>
		<input id="website_url" type="hidden" value="<?php echo $this->websiteUrl?>" />
<div class="seotoaster container_12 rounded3px"> <!-- w600 h580  -->
	<div class="header">
    <div class="closebutton">
		<span class="help">
			<a href="http://www.seotoaster.com/local-search-engine-optimization.html" target="_blank">Help</a>
		</span>
		<span class="close">Close</span>
	</div>
    Website ID Card
  </div>
  <?php echo $this->partial('registrationForm.phtml', array(
						'websiteUrl' => $this->websiteUrl,
						'organizationName' => $this->organizationName,
						'organizationDescription' => $this->organizationDescription,
						'organizationCountry' => $this->organizationCountry,
						'address1' => $this->address1,
						'address2' => $this->address2,
						'city' => $this->city,
						'countryState' => $this->countryState,
						'zip' => $this->zip,
						'phone' => $this->phone,
						'email' => $this->email,
						'fbAccount' => $this->fbAccount,
						'twitAccount' => $this->twitAccount,
						'countryList' => $this->countryList,
						'stateList' => $this->stateList,
						'industryType' => $this->industryType,
						'business' => $this->business,
						'toasterLang' => $this->toasterLang,
						'langList' => $this->langList,
						'corporateLogo' => $this->corporateLogo,
						'sambaToken' => $this->sambaToken,
						'industryList' => $this->industryList,
						'paymentTypes' => $this->paymentTypes,
						'paymentType' => $this->paymentType,
						'payOnline' => $this->payOnline,
						'agreement' => $this->agreement,
						'analyticsType' => $this->analyticsType,
						'analyticsTypeUseGA' => $this->analyticsTypeUseGA,
						'waCode' => $this->waCode,
						'widcardErr' => $this->errors,
						'widcardMessage' => $this->widcardMessage
					));
  ?>
</div>
</body>
</html>