<li class="cpanelsubtitle"><?php echo $this->translate('This news post'); ?></li>
<li><a href="javascript:;" data-url="<?php echo $this->websiteUrl; ?>/plugin/newslog/run/news/#edit/<?php echo $this->newsPostId; ?>" data-pheight="574" class="tpopup"><?php echo $this->translate('Edit this news post'); ?></a></li>
<li><a href="javascript:;" id="newslog-delete-post" data-nid="<?php echo $this->newsPostId; ?>"><?php echo $this->translate('Delete this post'); ?></a></li>
<li class="cpanelsubtitle"><?php echo $this->translate('Other posts'); ?></li>